config/routes.rb
Rails.application.routes.draw do

  resources :journeys, only: [:index, :new, :create, :show]

  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/journey.rb
class Journey < ApplicationRecord

  validates :leaving_time, :name, presence: true

  has_many :routes, inverse_of: :journey,  dependent: :destroy
  accepts_nested_attributes_for :routes, allow_destroy: true

  def get_init_time
    all_routes_time = self.routes.map{ |r| r.duration_in_minutes}
    self.leaving_time + all_routes_time.sum.minutes
  end
end

app/models/location.rb
class Location < ApplicationRecord
  validates :address, presence: true

  geocoded_by :address      
  after_validation :geocode 

  def to_geo
    [self.latitude, self.longitude].join(',')
  end
end

app/models/route.rb
class Route < ApplicationRecord
  require 'exceptions'

  belongs_to :journey

  belongs_to :init_location, :class_name => 'Location', optional: true
  belongs_to :end_location, :class_name => 'Location', optional: true

  accepts_nested_attributes_for :init_location, allow_destroy: true, reject_if:  ->(attrs) { attrs['address'].blank?}
  accepts_nested_attributes_for :end_location, allow_destroy: true, reject_if:  ->(attrs) { attrs['address'].blank?}  
  before_save :calculate_arrival_time


  private
  def calculate_arrival_time
    response = ApplicationController.helpers.get_request_to_json('/api/1/traveltime/',
      {'startcoord': self.init_location.to_geo,
        'endcoord': self.end_location.to_geo,
        'time': self.journey.leaving_time})
    if response.code === 200
      mins = JSON.parse(response.to_json)['travel_time_minutes']
      self.arrival_time = self.journey.get_init_time + mins.minutes
      binding.pry
    else
      raise Exceptions::ThirdPartyAPIError.new
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController
  require 'exceptions'
  def index
    @journeys = Journey.all
    
  end

  def new
    @journey = Journey.new
  end

  def create
    
    @journey = Journey.create(journey_params)
    
    if@journey.save
      redirect_to journey_path(@journey)
      flash[:notice] = "Journey created successfully"
    else
      @errors = @journey.errors
      render 'new'
    end

    rescue Exceptions::ThirdPartyAPIError => e
      flash[:alert] = e.message
      @journey = Journey.new(journey_params)
      render 'new'
  end

  def show
    @journey = Journey.includes(:routes).find(params[:id])
  end

  private

  def journey_params
    params.require(:journey).permit(:leaving_date, :leaving_time, :name, 
      routes_attributes: [:id, :time_on_location, :_destroy, 
        init_location_attributes: [:id, :address, :_destroy],
        end_location_attributes: [:id, :address, :_destroy]])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  require 'httparty'
  require 'json'

  BASE_URL = 'https://developer.citymapper.com'

  def get_request_to_json(root_path, query = {})
    query_string = query.map{|k,v| "#{k}=#{v}"}.join("&")
    query_string +="&key=#{ENV['CITYMAPPER_KEY']}"
    path = query.empty?? root_path : "#{root_path}?#{query_string}"
    response = HTTParty.get(BASE_URL+path)
    response
  end
end

app/helpers/form_helper.rb
module FormHelper
  def setup_journey(journey)
    journey.routes.build if journey.routes.empty?
    journey.routes.first.init_location = Location.new(address: ENV['OFFICE_ADDRESS'])
    journey.routes.first.end_location = Location.new
    journey
  end  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/journey_helper.rb
module JourneyHelper
end

app/views/home/index.html.haml
%h1
  Welcome

= link_to 'New Journey', new_journey_path

app/views/journeys/_route_fields.html.haml
.nested-fields
  = f.simple_fields_for :init_location, (f.object.init_location || Location.new) do |ff|
    = ff.input :address, placeholder: "Magallanes 989"
  = f.simple_fields_for :end_location, (f.object.end_location || Location.new) do |ff|
    = ff.input :address, placeholder: "Viale Ortigara 6"
  = link_to_remove_association "Remove route", f

app/views/journeys/index.html.haml
%h1 Journeys
%p= link_to "Add a New Journey", new_journey_path, class: "btn btn-primary"
%ul#journeys
  - @journeys.each do |journey|
    %li.journey{"data-id" => "#{journey.id}"}
      = link_to journey.name, journey_path(journey)

app/views/journeys/new.html.haml
%h1 New Journey Form
= render 'shared/errors', object: @journey

= simple_form_for setup_journey(@journey) do |f|
  = f.input :name, placeholder: "Mateo Andres"
  = f.input :leaving_time
  %h3 Routes
  #routes
    = f.simple_fields_for :routes do |route|
      = render 'route_fields', f: route
    .links
      = link_to_add_association 'Add Route', f, :routes
  = f.submit

= link_to "Back", journeys_path

app/views/journeys/show.html.haml
%label{ :style => "text-decoration: underline;"}
  Name:
%p  
  = @journey.name
%br/
%label{ :style => "text-decoration: underline;"}
  Leaving Time:
%strong
  = @journey.leaving_time
%br/

%h4{ :style => "color: grey;"}
  Routes
%table.table.table-dark
  %thead
    %tr
      %th{:scope => "col"} Departure
      %th{:scope => "col"} Arrival
      %th{:scope => "col"} Arrival time Aprox.
  %tbody
  - @journey.routes.each do |route|
    %tr
      %td= route.init_location.address
      %td= route.end_location.address
      %td= route.arrival_time

= link_to "Back", journeys_path

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Travel Time"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", media: "all"
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{ data: { target: ".nav-collapse", toggle: "collapse"} }
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{href: "/"} Travel Time
          .container.nav-collapse
            %ul.nav
              %li= link_to "Journeys", journeys_path

    .container
      = render partial: "shared/messages"
      .content
        .row
          .span12
            = yield

      %footer
        %p
          © A Rentify Company #{DateTime.now.year}
    = javascript_include_tag "application"

app/views/shared/_errors.html.haml
- if object.errors.any?
  #error_explanation
    %strong
      = pluralize(object.errors.count, 'error')
      were found

    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_messages.html.haml
- if notice
  %p.alert.alert-success
    = notice
    %span.pull-right
      %a.close{data: { dismiss: "alert" }, href: "#"} ×
- if alert
  %p.alert.alert-danger
    = alert
    %span.pull-right
      %a.close{data: { dismiss: "alert" }, href: "#"} ×